// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: contractModel.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: json:"user_id"
	UserId uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"house_id"
	HouseId uint32 `protobuf:"varint,3,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	// @inject_tag: json:"cycle"
	Cycle uint32 `protobuf:"varint,4,opt,name=Cycle,proto3" json:"Cycle,omitempty"`
	// @inject_tag: json:"status"
	Status string `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	// @inject_tag: json:"start_at"
	StartAt string `protobuf:"bytes,6,opt,name=StartAt,proto3" json:"StartAt,omitempty"`
	// @inject_tag: json:"end_at"
	EndAt string `protobuf:"bytes,7,opt,name=EndAt,proto3" json:"EndAt,omitempty"`
	// @inject_tag: json:"money"
	Money float32 `protobuf:"fixed32,8,opt,name=Money,proto3" json:"Money,omitempty"`
	// @inject_tag: json:"period"
	Period uint32 `protobuf:"varint,9,opt,name=Period,proto3" json:"Period,omitempty"`
	// @inject_tag: json:"period_unit"
	PeriodUnit string `protobuf:"bytes,10,opt,name=PeriodUnit,proto3" json:"PeriodUnit,omitempty"`
	// @inject_tag: json:"remark"
	Remark string `protobuf:"bytes,11,opt,name=Remark,proto3" json:"Remark,omitempty"`
	// @inject_tag: json:"deposit"
	Deposit float32 `protobuf:"fixed32,12,opt,name=Deposit,proto3" json:"Deposit,omitempty"`
	// @inject_tag: json:"owner_money"
	OwnerMoney float32 `protobuf:"fixed32,13,opt,name=OwnerMoney,proto3" json:"OwnerMoney,omitempty"`
	// @inject_tag: json:"owner_user_id"
	OwnerUserId uint32 `protobuf:"varint,14,opt,name=OwnerUserId,proto3" json:"OwnerUserId,omitempty"`
}

func (x *ContractModel) Reset() {
	*x = ContractModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contractModel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractModel) ProtoMessage() {}

func (x *ContractModel) ProtoReflect() protoreflect.Message {
	mi := &file_contractModel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractModel.ProtoReflect.Descriptor instead.
func (*ContractModel) Descriptor() ([]byte, []int) {
	return file_contractModel_proto_rawDescGZIP(), []int{0}
}

func (x *ContractModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContractModel) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContractModel) GetHouseId() uint32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *ContractModel) GetCycle() uint32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *ContractModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContractModel) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *ContractModel) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *ContractModel) GetMoney() float32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *ContractModel) GetPeriod() uint32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *ContractModel) GetPeriodUnit() string {
	if x != nil {
		return x.PeriodUnit
	}
	return ""
}

func (x *ContractModel) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ContractModel) GetDeposit() float32 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *ContractModel) GetOwnerMoney() float32 {
	if x != nil {
		return x.OwnerMoney
	}
	return 0
}

func (x *ContractModel) GetOwnerUserId() uint32 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

var File_contractModel_proto protoreflect.FileDescriptor

var file_contractModel_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xf1, 0x02, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x79,
	0x63, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x07, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0a, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x1b, 0x5a,
	0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_contractModel_proto_rawDescOnce sync.Once
	file_contractModel_proto_rawDescData = file_contractModel_proto_rawDesc
)

func file_contractModel_proto_rawDescGZIP() []byte {
	file_contractModel_proto_rawDescOnce.Do(func() {
		file_contractModel_proto_rawDescData = protoimpl.X.CompressGZIP(file_contractModel_proto_rawDescData)
	})
	return file_contractModel_proto_rawDescData
}

var file_contractModel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contractModel_proto_goTypes = []interface{}{
	(*ContractModel)(nil), // 0: pb.ContractModel
}
var file_contractModel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contractModel_proto_init() }
func file_contractModel_proto_init() {
	if File_contractModel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contractModel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contractModel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contractModel_proto_goTypes,
		DependencyIndexes: file_contractModel_proto_depIdxs,
		MessageInfos:      file_contractModel_proto_msgTypes,
	}.Build()
	File_contractModel_proto = out.File
	file_contractModel_proto_rawDesc = nil
	file_contractModel_proto_goTypes = nil
	file_contractModel_proto_depIdxs = nil
}
