// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: smsRecordModel.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmsRecordModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: json:"content"
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	// @inject_tag: json:"status"
	Status string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	// @inject_tag: json:"user_id"
	UserId uint32 `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"error"
	Error string `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
	// @inject_tag: json:"created_at"
	CreatedAt string `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	// @inject_tag: json:"house_id"
	HouseId uint32 `protobuf:"varint,7,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	// @inject_tag: json:"contract_id"
	ContractId uint32 `protobuf:"varint,8,opt,name=ContractId,proto3" json:"ContractId,omitempty"`
	// @inject_tag: json:"record_id"
	RecordId uint32 `protobuf:"varint,9,opt,name=RecordId,proto3" json:"RecordId,omitempty"`
}

func (x *SmsRecordModel) Reset() {
	*x = SmsRecordModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsRecordModel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsRecordModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsRecordModel) ProtoMessage() {}

func (x *SmsRecordModel) ProtoReflect() protoreflect.Message {
	mi := &file_smsRecordModel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsRecordModel.ProtoReflect.Descriptor instead.
func (*SmsRecordModel) Descriptor() ([]byte, []int) {
	return file_smsRecordModel_proto_rawDescGZIP(), []int{0}
}

func (x *SmsRecordModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SmsRecordModel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SmsRecordModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SmsRecordModel) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SmsRecordModel) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SmsRecordModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SmsRecordModel) GetHouseId() uint32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *SmsRecordModel) GetContractId() uint32 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

func (x *SmsRecordModel) GetRecordId() uint32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

var File_smsRecordModel_proto protoreflect.FileDescriptor

var file_smsRecordModel_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6d, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xf4, 0x01, 0x0a, 0x0e, 0x53,
	0x6d, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49,
	0x64, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smsRecordModel_proto_rawDescOnce sync.Once
	file_smsRecordModel_proto_rawDescData = file_smsRecordModel_proto_rawDesc
)

func file_smsRecordModel_proto_rawDescGZIP() []byte {
	file_smsRecordModel_proto_rawDescOnce.Do(func() {
		file_smsRecordModel_proto_rawDescData = protoimpl.X.CompressGZIP(file_smsRecordModel_proto_rawDescData)
	})
	return file_smsRecordModel_proto_rawDescData
}

var file_smsRecordModel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smsRecordModel_proto_goTypes = []interface{}{
	(*SmsRecordModel)(nil), // 0: pb.SmsRecordModel
}
var file_smsRecordModel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smsRecordModel_proto_init() }
func file_smsRecordModel_proto_init() {
	if File_smsRecordModel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smsRecordModel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsRecordModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smsRecordModel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smsRecordModel_proto_goTypes,
		DependencyIndexes: file_smsRecordModel_proto_depIdxs,
		MessageInfos:      file_smsRecordModel_proto_msgTypes,
	}.Build()
	File_smsRecordModel_proto = out.File
	file_smsRecordModel_proto_rawDesc = nil
	file_smsRecordModel_proto_goTypes = nil
	file_smsRecordModel_proto_depIdxs = nil
}
