// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: houseGroupService.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HouseGroupIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HouseGroupIndexRequest) Reset() {
	*x = HouseGroupIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houseGroupService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseGroupIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseGroupIndexRequest) ProtoMessage() {}

func (x *HouseGroupIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_houseGroupService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseGroupIndexRequest.ProtoReflect.Descriptor instead.
func (*HouseGroupIndexRequest) Descriptor() ([]byte, []int) {
	return file_houseGroupService_proto_rawDescGZIP(), []int{0}
}

type HouseGroupIndexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseGroupModel []*HouseGroupModel `protobuf:"bytes,1,rep,name=HouseGroupModel,proto3" json:"HouseGroupModel,omitempty"`
}

func (x *HouseGroupIndexResponse) Reset() {
	*x = HouseGroupIndexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houseGroupService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseGroupIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseGroupIndexResponse) ProtoMessage() {}

func (x *HouseGroupIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_houseGroupService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseGroupIndexResponse.ProtoReflect.Descriptor instead.
func (*HouseGroupIndexResponse) Descriptor() ([]byte, []int) {
	return file_houseGroupService_proto_rawDescGZIP(), []int{1}
}

func (x *HouseGroupIndexResponse) GetHouseGroupModel() []*HouseGroupModel {
	if x != nil {
		return x.HouseGroupModel
	}
	return nil
}

type HouseGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"name" form:"name" uri:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// @inject_tag: json:"user_id" form:"user_id" uri:"user_id"
	UserId uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"group_id" form:"group_id" uri:"group_id"
	GroupId uint32 `protobuf:"varint,3,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	// @inject_tag: json:"house_id" form:"house_id" uri:"house_id"
	HouseId uint32 `protobuf:"varint,4,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
}

func (x *HouseGroupRequest) Reset() {
	*x = HouseGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houseGroupService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseGroupRequest) ProtoMessage() {}

func (x *HouseGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_houseGroupService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseGroupRequest.ProtoReflect.Descriptor instead.
func (*HouseGroupRequest) Descriptor() ([]byte, []int) {
	return file_houseGroupService_proto_rawDescGZIP(), []int{2}
}

func (x *HouseGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HouseGroupRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HouseGroupRequest) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *HouseGroupRequest) GetHouseId() uint32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

type HouseGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseGroupModel *HouseGroupModel `protobuf:"bytes,1,opt,name=HouseGroupModel,proto3" json:"HouseGroupModel,omitempty"`
	Code            uint32           `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *HouseGroupResponse) Reset() {
	*x = HouseGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houseGroupService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseGroupResponse) ProtoMessage() {}

func (x *HouseGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_houseGroupService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseGroupResponse.ProtoReflect.Descriptor instead.
func (*HouseGroupResponse) Descriptor() ([]byte, []int) {
	return file_houseGroupService_proto_rawDescGZIP(), []int{3}
}

func (x *HouseGroupResponse) GetHouseGroupModel() *HouseGroupModel {
	if x != nil {
		return x.HouseGroupModel
	}
	return nil
}

func (x *HouseGroupResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_houseGroupService_proto protoreflect.FileDescriptor

var file_houseGroupService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x15, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x58,
	0x0a, 0x17, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0f, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x73, 0x0a, 0x11, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x22, 0x67, 0x0a,
	0x12, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x0f, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x32, 0xac, 0x02, 0x0a, 0x11, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x05,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x05, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_houseGroupService_proto_rawDescOnce sync.Once
	file_houseGroupService_proto_rawDescData = file_houseGroupService_proto_rawDesc
)

func file_houseGroupService_proto_rawDescGZIP() []byte {
	file_houseGroupService_proto_rawDescOnce.Do(func() {
		file_houseGroupService_proto_rawDescData = protoimpl.X.CompressGZIP(file_houseGroupService_proto_rawDescData)
	})
	return file_houseGroupService_proto_rawDescData
}

var file_houseGroupService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_houseGroupService_proto_goTypes = []interface{}{
	(*HouseGroupIndexRequest)(nil),  // 0: pb.HouseGroupIndexRequest
	(*HouseGroupIndexResponse)(nil), // 1: pb.HouseGroupIndexResponse
	(*HouseGroupRequest)(nil),       // 2: pb.HouseGroupRequest
	(*HouseGroupResponse)(nil),      // 3: pb.HouseGroupResponse
	(*HouseGroupModel)(nil),         // 4: pb.HouseGroupModel
}
var file_houseGroupService_proto_depIdxs = []int32{
	4, // 0: pb.HouseGroupIndexResponse.HouseGroupModel:type_name -> pb.HouseGroupModel
	4, // 1: pb.HouseGroupResponse.HouseGroupModel:type_name -> pb.HouseGroupModel
	2, // 2: pb.HouseGroupService.Index:input_type -> pb.HouseGroupRequest
	2, // 3: pb.HouseGroupService.Create:input_type -> pb.HouseGroupRequest
	2, // 4: pb.HouseGroupService.Remove:input_type -> pb.HouseGroupRequest
	2, // 5: pb.HouseGroupService.Join:input_type -> pb.HouseGroupRequest
	2, // 6: pb.HouseGroupService.Leave:input_type -> pb.HouseGroupRequest
	3, // 7: pb.HouseGroupService.Index:output_type -> pb.HouseGroupResponse
	3, // 8: pb.HouseGroupService.Create:output_type -> pb.HouseGroupResponse
	3, // 9: pb.HouseGroupService.Remove:output_type -> pb.HouseGroupResponse
	3, // 10: pb.HouseGroupService.Join:output_type -> pb.HouseGroupResponse
	3, // 11: pb.HouseGroupService.Leave:output_type -> pb.HouseGroupResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_houseGroupService_proto_init() }
func file_houseGroupService_proto_init() {
	if File_houseGroupService_proto != nil {
		return
	}
	file_houseGroupModel_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_houseGroupService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseGroupIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_houseGroupService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseGroupIndexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_houseGroupService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_houseGroupService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_houseGroupService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_houseGroupService_proto_goTypes,
		DependencyIndexes: file_houseGroupService_proto_depIdxs,
		MessageInfos:      file_houseGroupService_proto_msgTypes,
	}.Build()
	File_houseGroupService_proto = out.File
	file_houseGroupService_proto_rawDesc = nil
	file_houseGroupService_proto_goTypes = nil
	file_houseGroupService_proto_depIdxs = nil
}
