// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: houseModel.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HouseModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: json:"user_id"
	UserId uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"title"
	Title string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	// @inject_tag: json:"cycle"
	Cycle uint32 `protobuf:"varint,4,opt,name=Cycle,proto3" json:"Cycle,omitempty"`
	// @inject_tag: json:"contract_id"
	ContractId uint32 `protobuf:"varint,5,opt,name=ContractId,proto3" json:"ContractId,omitempty"`
	// @inject_tag: json:"status"
	Status string `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	// @inject_tag: json:"money"
	Money float32 `protobuf:"fixed32,7,opt,name=Money,proto3" json:"Money,omitempty"`
	// @inject_tag: json:"created_at"
	CreatedAt string `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	// @inject_tag: json:"province"
	Province string `protobuf:"bytes,9,opt,name=Province,proto3" json:"Province,omitempty"`
	// @inject_tag: json:"city"
	City string `protobuf:"bytes,10,opt,name=City,proto3" json:"City,omitempty"`
	// @inject_tag: json:"region"
	Region string `protobuf:"bytes,11,opt,name=Region,proto3" json:"Region,omitempty"`
	// @inject_tag: json:"linkname"
	Linkname string `protobuf:"bytes,12,opt,name=Linkname,proto3" json:"Linkname,omitempty"`
	// @inject_tag: json:"linkphone"
	Linkphone string `protobuf:"bytes,13,opt,name=Linkphone,proto3" json:"Linkphone,omitempty"`
	// @inject_tag: json:"remark"
	Remark string `protobuf:"bytes,14,opt,name=Remark,proto3" json:"Remark,omitempty"`
}

func (x *HouseModel) Reset() {
	*x = HouseModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houseModel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseModel) ProtoMessage() {}

func (x *HouseModel) ProtoReflect() protoreflect.Message {
	mi := &file_houseModel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseModel.ProtoReflect.Descriptor instead.
func (*HouseModel) Descriptor() ([]byte, []int) {
	return file_houseModel_proto_rawDescGZIP(), []int{0}
}

func (x *HouseModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseModel) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HouseModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HouseModel) GetCycle() uint32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *HouseModel) GetContractId() uint32 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

func (x *HouseModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HouseModel) GetMoney() float32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *HouseModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HouseModel) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *HouseModel) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *HouseModel) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *HouseModel) GetLinkname() string {
	if x != nil {
		return x.Linkname
	}
	return ""
}

func (x *HouseModel) GetLinkphone() string {
	if x != nil {
		return x.Linkphone
	}
	return ""
}

func (x *HouseModel) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_houseModel_proto protoreflect.FileDescriptor

var file_houseModel_proto_rawDesc = []byte{
	0x0a, 0x10, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xe6, 0x02, 0x0a, 0x0a, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x69, 0x6e,
	0x6b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x69,
	0x6e, 0x6b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x42,
	0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_houseModel_proto_rawDescOnce sync.Once
	file_houseModel_proto_rawDescData = file_houseModel_proto_rawDesc
)

func file_houseModel_proto_rawDescGZIP() []byte {
	file_houseModel_proto_rawDescOnce.Do(func() {
		file_houseModel_proto_rawDescData = protoimpl.X.CompressGZIP(file_houseModel_proto_rawDescData)
	})
	return file_houseModel_proto_rawDescData
}

var file_houseModel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_houseModel_proto_goTypes = []interface{}{
	(*HouseModel)(nil), // 0: pb.HouseModel
}
var file_houseModel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_houseModel_proto_init() }
func file_houseModel_proto_init() {
	if File_houseModel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_houseModel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_houseModel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_houseModel_proto_goTypes,
		DependencyIndexes: file_houseModel_proto_depIdxs,
		MessageInfos:      file_houseModel_proto_msgTypes,
	}.Build()
	File_houseModel_proto = out.File
	file_houseModel_proto_rawDesc = nil
	file_houseModel_proto_goTypes = nil
	file_houseModel_proto_depIdxs = nil
}
