// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: houseGroupModel.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HouseGroupModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// @inject_tag: json:"status"
	Status string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	// @inject_tag: json:"user_id"
	UserId uint32 `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"created_at"
	CreatedAt string `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	// @inject_tag: json:"updated_at"
	UpdatedAt string `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *HouseGroupModel) Reset() {
	*x = HouseGroupModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houseGroupModel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseGroupModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseGroupModel) ProtoMessage() {}

func (x *HouseGroupModel) ProtoReflect() protoreflect.Message {
	mi := &file_houseGroupModel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseGroupModel.ProtoReflect.Descriptor instead.
func (*HouseGroupModel) Descriptor() ([]byte, []int) {
	return file_houseGroupModel_proto_rawDescGZIP(), []int{0}
}

func (x *HouseGroupModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseGroupModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HouseGroupModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HouseGroupModel) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HouseGroupModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HouseGroupModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type HouseGroupRelationModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: json:"house_id"
	HouseId uint32 `protobuf:"varint,2,opt,name=HouseId,proto3" json:"HouseId,omitempty"`
	// @inject_tag: json:"group_id"
	GroupId uint32 `protobuf:"varint,3,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	// @inject_tag: json:"created_at"
	CreatedAt string `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	// @inject_tag: json:"updated_at"
	UpdatedAt string `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *HouseGroupRelationModel) Reset() {
	*x = HouseGroupRelationModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houseGroupModel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseGroupRelationModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseGroupRelationModel) ProtoMessage() {}

func (x *HouseGroupRelationModel) ProtoReflect() protoreflect.Message {
	mi := &file_houseGroupModel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseGroupRelationModel.ProtoReflect.Descriptor instead.
func (*HouseGroupRelationModel) Descriptor() ([]byte, []int) {
	return file_houseGroupModel_proto_rawDescGZIP(), []int{1}
}

func (x *HouseGroupRelationModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseGroupRelationModel) GetHouseId() uint32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *HouseGroupRelationModel) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *HouseGroupRelationModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HouseGroupRelationModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_houseGroupModel_proto protoreflect.FileDescriptor

var file_houseGroupModel_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa1, 0x01, 0x0a, 0x0f,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x99, 0x01, 0x0a, 0x17, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x1b, 0x5a, 0x19, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_houseGroupModel_proto_rawDescOnce sync.Once
	file_houseGroupModel_proto_rawDescData = file_houseGroupModel_proto_rawDesc
)

func file_houseGroupModel_proto_rawDescGZIP() []byte {
	file_houseGroupModel_proto_rawDescOnce.Do(func() {
		file_houseGroupModel_proto_rawDescData = protoimpl.X.CompressGZIP(file_houseGroupModel_proto_rawDescData)
	})
	return file_houseGroupModel_proto_rawDescData
}

var file_houseGroupModel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_houseGroupModel_proto_goTypes = []interface{}{
	(*HouseGroupModel)(nil),         // 0: pb.HouseGroupModel
	(*HouseGroupRelationModel)(nil), // 1: pb.HouseGroupRelationModel
}
var file_houseGroupModel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_houseGroupModel_proto_init() }
func file_houseGroupModel_proto_init() {
	if File_houseGroupModel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_houseGroupModel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseGroupModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_houseGroupModel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseGroupRelationModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_houseGroupModel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_houseGroupModel_proto_goTypes,
		DependencyIndexes: file_houseGroupModel_proto_depIdxs,
		MessageInfos:      file_houseGroupModel_proto_msgTypes,
	}.Build()
	File_houseGroupModel_proto = out.File
	file_houseGroupModel_proto_rawDesc = nil
	file_houseGroupModel_proto_goTypes = nil
	file_houseGroupModel_proto_depIdxs = nil
}
