// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: smsConfigModel.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmsConfigModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: json:"user_id"
	UserId uint32 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"status"
	Status string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	// @inject_tag: json:"available"
	Available uint32 `protobuf:"varint,4,opt,name=Available,proto3" json:"Available,omitempty"`
	// @inject_tag: json:"total"
	Total uint32 `protobuf:"varint,5,opt,name=Total,proto3" json:"Total,omitempty"`
	// @inject_tag: json:"day" form:"day" uri:"day"
	Day string `protobuf:"bytes,6,opt,name=Day,proto3" json:"Day,omitempty"`
	// @inject_tag: json:"expiration" form:"expiration" uri:"expiration"
	Expiration uint32 `protobuf:"varint,7,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
}

func (x *SmsConfigModel) Reset() {
	*x = SmsConfigModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smsConfigModel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsConfigModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsConfigModel) ProtoMessage() {}

func (x *SmsConfigModel) ProtoReflect() protoreflect.Message {
	mi := &file_smsConfigModel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsConfigModel.ProtoReflect.Descriptor instead.
func (*SmsConfigModel) Descriptor() ([]byte, []int) {
	return file_smsConfigModel_proto_rawDescGZIP(), []int{0}
}

func (x *SmsConfigModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SmsConfigModel) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SmsConfigModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SmsConfigModel) GetAvailable() uint32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *SmsConfigModel) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SmsConfigModel) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *SmsConfigModel) GetExpiration() uint32 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

var File_smsConfigModel_proto protoreflect.FileDescriptor

var file_smsConfigModel_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6d, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xb6, 0x01, 0x0a, 0x0e, 0x53,
	0x6d, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x44, 0x61, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smsConfigModel_proto_rawDescOnce sync.Once
	file_smsConfigModel_proto_rawDescData = file_smsConfigModel_proto_rawDesc
)

func file_smsConfigModel_proto_rawDescGZIP() []byte {
	file_smsConfigModel_proto_rawDescOnce.Do(func() {
		file_smsConfigModel_proto_rawDescData = protoimpl.X.CompressGZIP(file_smsConfigModel_proto_rawDescData)
	})
	return file_smsConfigModel_proto_rawDescData
}

var file_smsConfigModel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smsConfigModel_proto_goTypes = []interface{}{
	(*SmsConfigModel)(nil), // 0: pb.SmsConfigModel
}
var file_smsConfigModel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smsConfigModel_proto_init() }
func file_smsConfigModel_proto_init() {
	if File_smsConfigModel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smsConfigModel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsConfigModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smsConfigModel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smsConfigModel_proto_goTypes,
		DependencyIndexes: file_smsConfigModel_proto_depIdxs,
		MessageInfos:      file_smsConfigModel_proto_msgTypes,
	}.Build()
	File_smsConfigModel_proto = out.File
	file_smsConfigModel_proto_rawDesc = nil
	file_smsConfigModel_proto_goTypes = nil
	file_smsConfigModel_proto_depIdxs = nil
}
