redis:
  address: 127.0.0.1:6379
  password:

etcd:
  address: 127.0.0.1:2379

domain:
  sms: push

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: myuplus
  username: root
  password: 123456
  charset: utf8mb4